name: Deployment
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Continuous deployment
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install pipenv
        run: sudo pip3 install pipenv
      - name: Install python dependencies
        run: pipenv install --dev --python 3.8
      - name: Deploy to Pypi
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: python3 scripts/release.py
